# API Key Mapping - Maps common API names to your actual env variable names
API_KEY_MAPPING = {
  "NEWS_API": "NEWSAPI_KEY",
  "NEWSAPI_KEY": "NEWSAPI_KEY",
  "FINANCIAL_NEWS_API": "NEWSAPI_KEY",
  "FINANCIAL_API": "ALPHAVANTAGE_KEY",
  "ALPHA_VANTAGE": "ALPHAVANTAGE_KEY",
  "ALPHAVANTAGE_KEY": "ALPHAVANTAGE_KEY",
  "GEMINI_API": "GOOGLE_API_KEY",
  "GOOGLE_API_KEY": "GOOGLE_API_KEY",
  "WEB_SEARCH_API": "GOOGLE_API_KEY",
  "EMAIL_PASSWORD": "EMAIL_APP_PASSWORD",
  "EMAIL_APP_PASSWORD": "EMAIL_APP_PASSWORD",
  "EMAIL_APP": "EMAIL_APP",
  "SENDER_EMAIL": "EMAIL_APP"
}